apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-project-deploy
  labels:
    app: healthcare-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: healthcare-capstone-container
        image: yatish03/healthcare-project:
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-project-service
  labels:
    app: healthcare-app
spec:
  selector:
    app: healthcare-app
  type: NodePort
  ports:
  - nodePort: 31028
    port: 8081
    targetPort: 8081
